version: '3'
services:
  api:
    hostname: nork-town-cars
    build:
      context: ./
      dockerfile: dockerfile
    depends_on:
      - postgres
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/code
    networks:
      - nork-town-cars
    restart: unless-stopped
    ports:
        - 80:5000
    environment:
      DATABASE_CONNECTION_STRING: 

networks: 
  nork-town-cars:
    driver: bridge

